/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScienceExplanation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'summary' : IDL.Text,
  'steps' : IDL.Opt(IDL.Vec(IDL.Text)),
  'category' : IDL.Text,
  'safetyNotes' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const FoodPreservationTip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'author' : IDL.Principal,
  'updatedAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScienceExplanation' : IDL.Func([ScienceExplanation], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text))],
      [IDL.Nat],
      [],
    ),
  'deleteTip' : IDL.Func([IDL.Nat], [], []),
  'getAllScienceExplanations' : IDL.Func(
      [],
      [IDL.Vec(ScienceExplanation)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExplanationsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScienceExplanation)],
      ['query'],
    ),
  'getScienceExplanation' : IDL.Func(
      [IDL.Nat],
      [ScienceExplanation],
      ['query'],
    ),
  'getTip' : IDL.Func([IDL.Nat], [IDL.Opt(FoodPreservationTip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTips' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FoodPreservationTip)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTip' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text))],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScienceExplanation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'summary' : IDL.Text,
    'steps' : IDL.Opt(IDL.Vec(IDL.Text)),
    'category' : IDL.Text,
    'safetyNotes' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const FoodPreservationTip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'author' : IDL.Principal,
    'updatedAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScienceExplanation' : IDL.Func([ScienceExplanation], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text))],
        [IDL.Nat],
        [],
      ),
    'deleteTip' : IDL.Func([IDL.Nat], [], []),
    'getAllScienceExplanations' : IDL.Func(
        [],
        [IDL.Vec(ScienceExplanation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExplanationsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScienceExplanation)],
        ['query'],
      ),
    'getScienceExplanation' : IDL.Func(
        [IDL.Nat],
        [ScienceExplanation],
        ['query'],
      ),
    'getTip' : IDL.Func([IDL.Nat], [IDL.Opt(FoodPreservationTip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTips' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FoodPreservationTip)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTip' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Text))],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };