/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FoodPreservationTip {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'tags' : [] | [Array<string>],
  'author' : Principal,
  'updatedAt' : Time,
}
export interface ScienceExplanation {
  'id' : bigint,
  'title' : string,
  'summary' : string,
  'steps' : [] | [Array<string>],
  'category' : string,
  'safetyNotes' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScienceExplanation' : ActorMethod<[ScienceExplanation], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTip' : ActorMethod<[string, string, [] | [Array<string>]], bigint>,
  'deleteTip' : ActorMethod<[bigint], undefined>,
  'getAllScienceExplanations' : ActorMethod<[], Array<ScienceExplanation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExplanationsByCategory' : ActorMethod<
    [string],
    Array<ScienceExplanation>
  >,
  'getScienceExplanation' : ActorMethod<[bigint], ScienceExplanation>,
  'getTip' : ActorMethod<[bigint], [] | [FoodPreservationTip]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTips' : ActorMethod<[Principal], Array<FoodPreservationTip>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTip' : ActorMethod<
    [bigint, string, string, [] | [Array<string>]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];